In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
{"a" : [4, 5, 6],
"b" : [7, 8, 9],
"c" : [10, 11, 12]},
index = [1, 2, 3])

df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [8]:
df['a']

1    4
2    5
3    6
Name: a, dtype: int64

In [9]:
df[['a']]

   a
1  4
2  5
3  6

In [10]:
df[df['a']>4]

   a  b   c
2  5  8  11
3  6  9  12

In [ ]:
df['a']

In [11]:
df[["a",'b']]

   a  b
1  4  7
2  5  8
3  6  9

In [12]:
df['a'].value_counts()

a
4    1
5    1
6    1
Name: count, dtype: int64

In [13]:
len(df)

3

In [17]:
df.sort_values("a",ascending =False)

   a  b   c
3  6  9  12
2  5  8  11
1  4  7  10

In [ ]:
df=df.drop(['c'],axis=1)
dfv

   a  b
1  4  7
2  5  8
3  6  9